### ISSUE TITLE
HttpOnly ayarı yapılamıyor

### ISSUE THREAD

**Issue by efepolat** [ovunctukenmez/SameSiteSessionStarter#1]
HttpOnly hep false geliyor ve dışarıdan true olarak ayarlanamıyor.

**Comment by ovunctukenmez** [comment]
Merhaba,

session_set_cookie_params() fonksiyonu ile session_start() fonksiyonunun oluşturacağı cookie parametresi belirlenebilir.
https://www.php.net/manual/en/function.session-set-cookie-params.php

alternatif olarak ini_set() ile de çözülebilir.

**Comment by efepolat** [comment]
Teşekkürler. Sizin çözümünüzü payment gateway üzerinde bankaya dönüşte session verisi taşınamadığı için kullanmak istiyordum. Chrome 80 sürümünden sonra yapılan Samsite değişikliğinden dolayı session datası taşınamıyor. Fakat safari de samesite=none değerini görmezden geliyor. Sizin çözümünüz bu sorunumu çözebilir mi? Yani bu classı kullandığım taktirde payment gateway sorunumu cross-browser olarak çözebilir mi? Zaman ayırdığınız için tekrar teşekkür ederim

**Comment by ovunctukenmez** [comment]
Merhaba,
Rica ederim,
Safari tarayıcısı için bazı MacOS sürümlerinde genel bir problem var maalesef.
https://caniuse.com/same-site-cookie-attribute
isBrowserSameSiteCompatible() fonksiyonuyla tarayıcı desteği kontrol edilerek devam ediliyor.
Eğer önceden bir oturum açmışsanız sağlıklı bir test için oturum cookie'sini silmenizi öneririm.
https://github.com/ovunctukenmez/SameSiteSessionStarter#notes
Bu sınıf gerçek ortamda halihazırda kullanılıyor, eğer ters görünen bir durum var ise koda katkıda bulunabilirseniz sevinirim.
İyi çalışmalar

**Comment by efepolat** [comment]
Katkım olabilirse çok sevinirim. Ödeme sistemi (Iyzico) ile başım belada şuanda. Session üzerinde tuttuğum veriyi Iyzico'ya post request ile gönderiyorum. Fakat samesite sorunundan dolayı Iyzico'nun benim websiteme geri döndüğü sayfaya session verisini taşıyamıyor. Siz böyle bir problemle karşılaştınız mı hiç, karşılaştıysanız nasıl bir çözüm ürettiniz? Fazla uzatıp sıktıysam kusura bakmayın, affınıza sığınıyorum. Teşekkürler.

**Comment by ovunctukenmez** [comment]
Rica ederim,
Daha önceden session_start ile bir oturum başlatmışsanız ilgili cookie'yi silerek deneyebilirsiniz.
Manuel veya başlatıldığı parametrelerle geçmiş zamana atayarak silinmediği sürece tam olarak test edilemiyor çünkü karşılaştırma yaparken yeni parametre kullanılmıyor.
İstisnai durumdaki tarayıcı ve işletim sistemleri için bu şekilde bırakmak daha iyi çünkü bildiğim kadarıyla çözümü şu an için yok.
Zaten kullanım oranı çok yüksek değil.
Bahsettiğiniz ödeme akışı samesite: none kullanıldığında oturum kopması sorunu yaşamayacaktır.
Ek olarak; samesite:none sadece https protokolünde çalışıyor, bilginize.
İyi çalışmalar

**Comment by efepolat** [comment]
Zaman ayırdığınız için tekrar teşekkürler. İyi çalışmalar.

**Comment by ovunctukenmez** [comment]
Rica ederim, umarım kısa sürede entegrasyonu başarıyla tamamlarsınız.
İyi çalışmalar dilerim.
